organization:
  name: default
  
clusters:
  - id: default
    name: My Local Kafka Cluster
    color: "#0013E7"
    ignoreUntrustedCertificate: false
    bootstrapServers: "$KAFKA_BOOTSTRAP_SERVER"
    properties:
    schemaRegistry:
      url: "$SR_SERVER"
      ignoreUntrustedCertificate: false
      properties:
    labels: {}

admin:
  email: "admin@example.io"
  password: "admin"

sso:
  ldap:
    - name: "default"
      server: "ldap://openldap:1389"
      managerDn: "cn=admin,dc=example,dc=org"
      managerPassword: "adminpassword"
      search-subtree: true
      search-base: "ou=users,dc=example,dc=org"
      search-filter: "(uid={0})" # or "(cn={0})"
      search-attributes: ["uid", "cn", "mail", "email", "givenName", "sn", "displayName"]
      groups-enabled: true
      groups-base: "ou=groups,dc=example,dc=org"
      groups-filter: "(member={0})"
      groups-attribute: "cn"

license: "$LICENSE_KEY"
