organization:
  name: default
  
clusters:
  - id: default
    name: My Local Kafka Cluster
    color: "#0013E7"
    ignoreUntrustedCertificate: false
    bootstrapServers: "$KAFKA_BOOTSTRAP_SERVER"
    properties:
    schemaRegistry:
      url: "$SR_SERVER"
      ignoreUntrustedCertificate: false
      properties:
    labels: {}

auth:
  demo-users:
    - email: admin@conduktor.io
      password: admin
      groups:
        - ADMIN
    - email: user@conduktor.io
      password: user
      groups:
        - DEV
license: "$LICENSE_KEY"